---

- name: Automate provisioning of virtual macine's on Azure Cloud
  hosts: localhost
  connection: local

  vars_prompt:

    - name: resourcegroup
      prompt: "Enter the resource group name"
      private: no


    - name: virtualnetwork
      prompt: "Enter virtual network name"
      private: no

    - name: location
      prompt: "Enter location"
      private: no

    - name: passwordvm1
      prompt: "Enter local administrator password for vm1"
      private: no

    - name: passwordvm2
      prompt: "Enter local administrator password for vm2"
      private: no

    - name: subnet2
      prompt: "Enter first subnet name"
      private: no

    - name: subnet3
      prompt: "Enter second subnet name"
      private: no

  vars:
       - virtualmachine1: vm1
       - virtualmachine2: vm2

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resourcegroup }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resourcegroup }}"
        name: "{{ virtualnetwork }}"
        address_prefixes_cidr:
           - "10.2.0.0/16"

    - name: Add subnet2
      azure_rm_subnet:
        resource_group: "{{ resourcegroup }}"
        name: "{{ subnet2 }}"
        address_prefix_cidr: "10.2.1.0/24"
        virtual_network_name: "{{ virtualnetwork }}"
        state: present

    - name: Add subnet3
      azure_rm_subnet:
        resource_group: "{{ resourcegroup }}"
        name: "{{ subnet3 }}"
        address_prefix_cidr: "10.2.2.0/24"
        virtual_network_name: "{{ virtualnetwork }}"
        state: present

    - name: Create public IP address for vm1
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup }}"
        allocation_method: Static
        name: "{{ virtualmachine1 }}PIP"
        state: present
      register: output_ip_address_vm1

    - name: Show Public IP address for vm1
      debug:
        msg: "The public IP for vm1 is {{ output_ip_address_vm1.state.ip_address }}"


    - name: Create public IP address for vm2
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup }}"
        allocation_method: Static
        name: "{{ virtualmachine2 }}PIP"
        state: present
      register: output_ip_address_vm2


    - name: Show Public IP address for vm2
      debug:
        msg: "The public IP for vm1 is {{ output_ip_address_vm2.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resourcegroup }}"
        name: "{{ item }}"
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range: 
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound
      with_items:
               - "{{ virtualmachine1 }}NSG"
               - "{{ virtualmachine2 }}NSG"

    - name: Create a network interface for vm1
      azure_rm_networkinterface:
        name: "{{ virtualmachine1 }}NIC"
        resource_group: "{{ resourcegroup }}"
        virtual_network: "{{ virtualnetwork }}"
        subnet_name: "{{ subnet2 }}"
        security_group: "{{ virtualmachine1 }}NSG"
        state: present
        ip_configurations:
          - name: default
            public_ip_address_name: "{{ virtualmachine1 }}PIP"
            primary: True


    - name: Create a network interface for vm2
      azure_rm_networkinterface:
        name: "{{ virtualmachine2 }}NIC"
        resource_group: "{{ resourcegroup }}"
        virtual_network: "{{ virtualnetwork }}"
        subnet_name: "{{ subnet2 }}"
        security_group: "{{ virtualmachine2 }}NSG"
        state: present
        ip_configurations:
          - name: default
            public_ip_address_name: "{{ virtualmachine2 }}PIP"
            primary: True


    - name: Create a first VM1
      azure_rm_virtualmachine:
         resource_group: "{{ resourcegroup }}"
         name: "{{ virtualmachine1 }}"
         vm_size: Standard_B1ms
         managed_disk_type: Premium_LRS
         admin_username: chs_admin
         admin_password: "{{ passwordvm1 }}"
         network_interfaces: "{{ virtualmachine1 }}NIC"
         os_type: Windows
         subnet_name: "{{ subnet2 }}"
         image:
           offer: WindowsServer
           publisher: MicrosoftWindowsServer
           sku: 2016-Datacenter
           version: latest


    - name: Create a first VM2
      azure_rm_virtualmachine:
         resource_group: "{{ resourcegroup }}"
         name: "{{ virtualmachine2 }}"
         vm_size: Standard_B1ms
         managed_disk_type: Premium_LRS
         admin_username: chs_admin
         admin_password: "{{ passwordvm2 }}"
         network_interfaces: "{{ virtualmachine2 }}NIC"
         os_type: Windows
         subnet_name: "{{ subnet2 }}"
         image:
           offer: WindowsServer
           publisher: MicrosoftWindowsServer
           sku: 2016-Datacenter
           version: latest
